[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.2.2"
edition = "2024"
rust-version = "1.88"
authors = ["krteke"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/krteke/aura-anim-iced"
keywords = ["iced", "animation", "ui", "motion"]
categories = ["gui", "graphics"]

[workspace.dependencies]
iced = "0.14"
iced_core = "0.14"
lilt = "0.8.1"
palette = "0.7.6"
float-cmp = "0.10.0"
criterion = "0.8.2"
thiserror = "2.0.18"
aura-anim-core = { version = "0.2.2", path = "crates/aura-anim-core" }
aura-anim-iced = { version = "0.2.2", path = "crates/aura-anim-iced", default-features = false }
aura-anim-macros = { version = "0.2.2", path = "crates/aura-anim-macros" }

[workspace.lints.rust]
missing_docs = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_code = "forbid"
unreachable_pub = "warn"
unused_must_use = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
alloc_instead_of_core = "warn"
std_instead_of_core = "allow"
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
