[workspace]
resolver = "3"
members = ["crates/*"]

# [package]
# name = "aura-anim-iced"
# include = [
#     "src/**/*.rs",
#     "examples/**/*.rs",
#     "benches/**/*.rs",
#     "tests/**/*.rs",
#     "README.md",
#     "CHANGELOG.md",
#     "LICENSE",
#     "Cargo.toml",
# ]


[workspace.package]
version = "0.2.1"
edition = "2024"
rust-version = "1.88"
authors = ["krteke"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/krteke/aura-anim-iced"
description = "Iced-first animation primitives."
documentation = "https://docs.rs/aura-anim-iced"
keywords = ["iced", "animation", "ui", "motion"]
categories = ["gui", "graphics"]


# [lib]
# name = "aura_anim_iced"
# path = "crates/aura-anim/src/lib.rs"

# [[bench]]
# name = "sampling"
# harness = false

# [features]
# default = []
# palette = ["dep:palette"]
# spring = []
# widgets = []
# theme = []
# layout = []
# serde = ["dep:serde"]
# tracing = ["dep:tracing"]
# inspector = ["tracing"]

[workspace.dependencies]
iced = "0.14"
lilt = "0.8.1"
palette = "0.7.6"
# serde = { version = "1", optional = true, features = ["derive"] }
tracing = "0.1"
smallvec = "1.15.1"
rustc-hash = "2.1.2"
thiserror = "2"

# criterion = { version = "0.8.2", default-features = false }
# anyhow = "1"
# tracing-subscriber = "0.3"

[workspace.package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.lints.rust]
missing_docs = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_code = "forbid"
unreachable_pub = "warn"
unused_must_use = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
alloc_instead_of_core = "warn"
std_instead_of_core = "allow"
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
