[package]
name = "aura-anim-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Typed animation runtime and composable animation sources."
documentation = "https://docs.rs/aura-anim-core"

[features]
default = []
iced = ["dep:iced_core"]
rgba = ["iced"]
oklaba = ["iced", "dep:palette"]

[dependencies]
aura-anim-macros.workspace = true
iced_core = { workspace = true, optional = true }
lilt.workspace = true
palette = { workspace = true, optional = true }

[dev-dependencies]
float-cmp.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
features = ["iced", "rgba"]
rustdoc-args = ["--cfg", "docsrs"]
