[package]
name = "aura-anim-iced"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Iced integration for the aura typed animation runtime."
documentation = "https://docs.rs/aura-anim-iced"

[features]
default = ["rgba"]
rgba = ["aura-anim-core/rgba"]
oklaba = ["aura-anim-core/oklaba"]

[dependencies]
aura-anim-core = { workspace = true, features = ["iced"] }
iced = { workspace = true, features = ["tokio"] }

[lints]
workspace = true

[package.metadata.docs.rs]
features = ["rgba"]
rustdoc-args = ["--cfg", "docsrs"]
