[package]
name = "aura-anim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Convenience facade for aura animation core and Iced integration."
documentation = "https://docs.rs/aura-anim"

[features]
default = ["rgba"]
rgba = ["aura-anim-iced/rgba"]
oklaba = ["aura-anim-iced/oklaba"]
tracing = ["aura-anim-core/tracing", "aura-anim-iced/tracing"]

[dependencies]
aura-anim-core.workspace = true
aura-anim-iced.workspace = true

[dev-dependencies]
float-cmp.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
features = ["rgba", "tracing"]
rustdoc-args = ["--cfg", "docsrs"]
